'use client'

import type { Metadata } from 'next'
import './globals.css'
import { Poppins, Lora, Oswald } from '@next/font/google'

import Home from './page'
import Navigation from '@/components/Navigation/Navigation'
import Main from '@/components/Main/Main'
import Skills from '@/components/Skills/Skills'
import ProjectSection from '@/components/ProjectSection/ProjectSection'
import { useState } from 'react'

// export const metadata: Metadata = {
//   title: 'Ishan | Portfolio',
//   description: 'Generated by create next app',
// }
const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
})

const layout = ({ children }: { children: React.ReactNode }) => {
  const [theme, setTheme] = useState(true)

  return (
    <html>
      <body className={poppins.className} data-theme={theme ? 'dark' : 'light'}>
        <Navigation setTheme={setTheme} theme={theme} />
        <Main />
        <Skills />
        <ProjectSection />
        {/* {children} */}
      </body>
    </html>
  )
}

export default layout
